KCFinder_browse:
    path:  /kcfinder/browse.php
    defaults:
        _controller: "IkadocKCFinderBundle:Proxy:proxy"
        file: browse.php

KCFinder_upload:
    path:  /kcfinder/upload.php
    defaults:
        _controller: "IkadocKCFinderBundle:Proxy:proxy"
        file: upload.php

KCFinder_route:
    path:  /kcfinder/{file}
    defaults:
        _controller: "IkadocKCFinderBundle:Proxy:proxy"
    requirements:
        file: "favico\\.ico|browse\\.php|js_localize\\.php|upload\\.php|css/index\\.php|js/index\\.php|themes/[^\\.]*/css\\.php|themes/[^\\.]*/js\\.php|themes/[^\\.]*/img/[^\\.]*\\.(png|gif|jpg)"
